sosna/sdmx-rest4js

- src/index.coffee
- test/index.test.coffee
> fix(api): Fix issue with undefined SdmxPatterns

- src/metadata/metadata-type.coffee
- src/utils/api-version.coffee
- src/utils/url-generator.coffee
- test/metadata/metadata-query.test.coffee
- test/metadata/metadata-type.test.coffee
- test/utils/api-version.test.coffee
- test/utils/url-generator.test.coffee
> Add supports for v1.2.0 of the SDMX RESTful API

- package.json
- src/utils/url-generator.coffee
- test/utils/url-generator.test.coffee
> Added support for URLs without default values

- src/utils/url-generator.coffee
> refactor(url-generator): Lower complexity of createShortMetadataQuery

- src/utils/api-version.coffee
- test/utils/api-version.test.coffee
> feat(api-version): Add support for v1.3.0

- src/data/data-format.coffee
- test/data/data-format.test.coffee
Added support for SDMX-CSV and latest SDMX-JSON data formats
fix #58
> feat(data-format): Add support for new formats

- src/utils/url-generator.coffee
Reduced complexity of createShortDataQuery by splitting the handling of the path and query string
parameters
fix #68
> refactor(url-generator): Reduce complexity

- package.json
- src/index.coffee
- test/index.test.coffee
> Add option to retrieve full response

- .gitignore
- src/index.coffee
- src/utils/api-version.coffee
- test/index.test.coffee
- test/utils/api-version.test.coffee
The API now offers the possibility to get the list of valid resources for a particular version of
the RESTful API
> CR-86: Get resources for version 

- .travis.yml
- package.json
- src/utils/api-version.coffee
- test/utils/api-version.test.coffee
The `sort` function was returned instead of the expected resource array ;)
> Fix bug when getting resources

- .gitignore
- package.json
- src/index.coffee
- test/index.test.coffee
* Codes in the 300 range are no longer considered as invalid
* Code 100 is no longer considered as invalid
Fix #106
> Review checkStatus

- package.json
- src/utils/api-version.coffee
- test/utils/api-version.test.coffee
> checkStatus & checkMediaType

- .gitignore
- package.json
- src/metadata/metadata-format.coffee
- test/metadata/metadata-format.test.coffee
> Add support for SDMX-JSON Structure format 

- package.json
- src/index.coffee
- src/utils/api-version.coffee
- test/utils/api-version.test.coffee
> Add support for version 1.4.0 of the SDMX RESTful API

- .travis.yml
- package.json
- src/index.coffee
- src/schema/schema-context.coffee
- src/schema/schema-query.coffee
- src/utils/sdmx-patterns.coffee
- src/utils/url-generator.coffee
- test/data/data-query.test.coffee
- test/index.test.coffee
- test/metadata/metadata-query.test.coffee
- test/schema/schema-context.test.coffee
- test/schema/schema-query.test.coffee
- test/utils/url-generator.test.coffee
> Add support for schema queries

- .npmignore
- package.json
- src/index.coffee
- test/index.test.coffee
> getUrl supports schema queries

- package.json
- src/data/data-query.coffee
- src/utils/url-generator.coffee
- test/data/data-query.test.coffee
- test/index.test.coffee
- test/utils/url-generator.test.coffee
> Obs dimension no longer defaults to TIME_PERIOD

- package.json
- src/data/data-format.coffee
- test/data/data-format.test.coffee
> Add options for SDMX-CSV

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
- src/utils/api-version.coffee
- test/utils/api-version.test.coffee
> Add support for SDMX-REST 1.5.0

- .eslintrc
- src/avail/availability-query.coffee
- src/data/data-query.coffee
- src/index.coffee
- src/metadata/metadata-query.coffee
- src/service/service.coffee
- src/utils/url-generator.coffee
- src/utils/validators.coffee
- test/index.test.coffee
- test/service/service.test.coffee
> Add service formats for structure and schema queries

- package-lock.json
- package.json
- src/service/service.coffee
- test/service/service.test.coffee
> Add UNICEF to the list of providers

- package-lock.json
- package.json
- src/service/service.coffee
The BIS has launched his new [SDMX REST API](https://stats.bis.org/api-doc/v1/). 
The purpose of this pull request is to add the BIS service to the list of built-in providers.
> Add BIS provider

- package-lock.json
- package.json
- src/service/service.coffee
> Add BIS to the list of supported services

- src/schema/schema-context.coffee
- src/utils/api-version.coffee
- src/utils/sdmx-patterns.coffee
- src/utils/url-generator.coffee
- test/schema/schema-context.test.coffee
- test/schema/schema-query.test.coffee
- test/utils/api-version.test.coffee
- test/utils/url-generator.test.coffee
> Support SDMX 3.0 schema queries
